### ISSUE TITLE
problem with depencie pymongo

### ISSUE THREAD

**Issue by Clevero** [jakubroztocil/cloudtunes#34]
trying to install cloudtunes-server but pymongo needs to be donwgraded. i have on my debian testing machine python-pymongo=2.7.1-1 installed but exactly 2.7 is needed. so after if execute "cloudtunes-worker worker --loglevel=INFO -c 4 &" to start the server, there is a log messeage like "ImportError: Motor 0.2.1 requires PyMongo at exactly version 2.7. You have PyMongo 2.7.2.". 

why is exactly this version needed, and not also a newer version usable? my repo just have this version of pymongo and i don't want to install it manually with a .deb package or something

can anyone please update the code so that also newer versions can be used?

full error log:
marcel@Lara:~/cloudtunes/cloudtunes-server$ Traceback (most recent call last):
  File "/usr/local/bin/cloudtunes-worker", line 9, in <module>
    load_entry_point('cloudtunes==0.0.1', 'console_scripts', 'cloudtunes-worker')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/home/marcel/cloudtunes/cloudtunes-server/cloudtunes/__init__.py", line 10, in <module>
    from .users.models import User
  File "/home/marcel/cloudtunes/cloudtunes-server/cloudtunes/users/models.py", line 10, in <module>
    from cloudtunes import async
  File "/home/marcel/cloudtunes/cloudtunes-server/cloudtunes/async.py", line 4, in <module>
    import motor
  File "/usr/local/lib/python2.7/dist-packages/motor/__init__.py", line 56, in <module>
    raise ImportError(msg)
ImportError: Motor 0.2.1 requires PyMongo at exactly version 2.7. You have PyMongo 2.7.2.
^C
[1]+  Exit 1                  cloudtunes-worker worker --loglevel=INFO -c 4
marcel@Lara:~/cloudtunes/cloudtunes-server$

**Comment by jakubroztocil** [comment]
That is a requirement of the `motor` dependency. I believe it might be possible to install a newer version of motor (pip install -U motor) that isn't that strict about the PyMongo version. Otherwise try installing CloudTunes using virtualenv.
