### ISSUE TITLE
Failed to build docker image

### ISSUE THREAD

**Issue by crashtua** [jakubroztocil/cloudtunes#50]
When trying to build docker image I got following error:
```
npm WARN engine co@4.6.0: wanted: {"iojs":">= 1.0.0","node":">= 0.12.0"} (current: {"node":"0.10.48","npm":"2.15.1"})

> node-sass@3.8.0 install /home/cloudtunes/cloudtunes-webapp/node_modules/sass-brunch/node_modules/node-sass
> node scripts/install.js


/home/cloudtunes/cloudtunes-webapp/node_modules/sass-brunch/node_modules/node-sass/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/cloudtunes/cloudtunes-webapp/node_modules/sass-brunch/node_modules/node-sass/node_modules/request/node_modules/hawk/lib/index.js:5:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
npm ERR! Linux 4.10.0-26-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.10.48
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@3.8.0 install: `node scripts/install.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the node-sass@3.8.0 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cloudtunes/cloudtunes-webapp/npm-debug.log
The command '/bin/sh -c cd cloudtunes-webapp     && npm install     && brunch b --env config-dist.coffee' returned a non-zero code: 1
```

**Comment by TheGlitchr** [comment]
Something to do with sass
